/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Controllers.ControllerRequest;
import Controllers.PeticionesDAO;
import Controllers.RoundedCornerBorder;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author zooe_
 */
public class GUIGestor extends javax.swing.JFrame {
    private PeticionesDAO peticion = new ControllerRequest();
    Color borderColor = new Color(77, 77, 77);
    /**
     * Creates new form GUIGestor
     */
    public GUIGestor() {
        initComponents();
        peticion.selectUser(Table);
        Table.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                int fila = Table.getSelectedRow();
                if(fila >= 0){
                    InputIde.setText(Table.getValueAt(fila, 0).toString());
                    InputUser.setText(Table.getValueAt(fila, 1).toString());
                    InputPassword.setText(Table.getValueAt(fila, 2).toString());
                }
            }
        });
    }

    private void Clean(){
        InputIde.setText("");
        InputUser.setText("");
        InputPassword.setText("");
        Table.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        LabelIde = new javax.swing.JLabel();
        LabelUser = new javax.swing.JLabel();
        InputUser = new javax.swing.JTextField();
        LabelPassword = new javax.swing.JLabel();
        InputIde = new javax.swing.JTextField();
        ;
        InputPassword = new javax.swing.JTextField();
        ;
        jPanel3 = new javax.swing.JPanel();
        BtnInsert = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor");
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(840, 540));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(32, 66, 94));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestor de usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table);

        LabelIde.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelIde.setText("Id");
        LabelIde.setVisible(false);

        LabelUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelUser.setText("Usuario");

        InputUser.setBackground(new Color(169, 169, 169));
        InputIde.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18));
        InputUser.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        InputUser.setForeground(new java.awt.Color(51, 51, 51));
        InputUser.setBorder(new RoundedCornerBorder(10, borderColor));

        LabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelPassword.setText("Contraseña");

        InputIde.setEditable(false);
        InputIde.setBackground(new Color(169, 169, 169));
        InputIde.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        InputIde.setForeground(new java.awt.Color(51, 51, 51));
        InputIde.setBorder(new RoundedCornerBorder(10, borderColor));
        InputIde.setFocusable(false);
        InputIde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIdeActionPerformed(evt);
            }
        });
        InputIde.setVisible(false);

        InputPassword.setBackground(new Color(169, 169, 169));
        InputPassword.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        InputPassword.setForeground(new java.awt.Color(51, 51, 51));
        InputPassword.setBorder(new RoundedCornerBorder(10, borderColor));
        InputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LabelUser)
                        .addGap(53, 53, 53)
                        .addComponent(InputUser))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LabelPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                        .addComponent(LabelIde)
                        .addGap(18, 18, 18)
                        .addComponent(InputIde, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(InputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUser)
                    .addComponent(InputUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputIde, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelIde)
                    .addComponent(LabelPassword))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(81, Short.MAX_VALUE)
                    .addComponent(InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setVerifyInputWhenFocusTarget(false);

        BtnInsert.setBackground(new java.awt.Color(32, 66, 94));
        BtnInsert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnInsert.setForeground(new java.awt.Color(255, 255, 255));
        BtnInsert.setText("<html><div style='text-align:center;'>Insertar <br> usuarios</div></html>");
        BtnInsert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnInsert.setMaximumSize(new java.awt.Dimension(145, 32));
        BtnInsert.setMinimumSize(new java.awt.Dimension(145, 32));
        BtnInsert.setPreferredSize(new java.awt.Dimension(155, 65));
        BtnInsert.setBorder(new RoundedCornerBorder(10, Color.LIGHT_GRAY));
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });
        jPanel3.add(BtnInsert);

        BtnUpdate.setBackground(new java.awt.Color(32, 66, 94));
        BtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("<html><div style='text-align:center;'>Actualizar <br> usuario</div></html>");
        BtnUpdate.setMaximumSize(new java.awt.Dimension(145, 32));
        BtnUpdate.setMinimumSize(new java.awt.Dimension(145, 32));
        BtnUpdate.setPreferredSize(new java.awt.Dimension(155, 65));
        BtnInsert.setBorder(new RoundedCornerBorder(10, Color.LIGHT_GRAY));
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(BtnUpdate);

        BtnDelete.setBackground(new java.awt.Color(32, 66, 94));
        BtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelete.setText("<html><div style='text-align:center;'>Eliminar <br> usuario</div></html>");
        BtnDelete.setMaximumSize(new java.awt.Dimension(145, 32));
        BtnDelete.setMinimumSize(new java.awt.Dimension(145, 32));
        BtnDelete.setPreferredSize(new java.awt.Dimension(155, 65));
        BtnInsert.setBorder(new RoundedCornerBorder(10, Color.LIGHT_GRAY));
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(BtnDelete);

        BtnList.setBackground(new java.awt.Color(32, 66, 94));
        BtnList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnList.setForeground(new java.awt.Color(255, 255, 255));
        BtnList.setText("<html><div style='text-align:center;'>Actualizar lista <br>de usuarios</div></html>");
        BtnList.setMaximumSize(new java.awt.Dimension(145, 32));
        BtnList.setMinimumSize(new java.awt.Dimension(145, 32));
        BtnList.setPreferredSize(new java.awt.Dimension(155, 65));
        BtnInsert.setBorder(new RoundedCornerBorder(10, Color.LIGHT_GRAY));
        BtnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListActionPerformed(evt);
            }
        });
        BtnList.setVisible(false);
        jPanel3.add(BtnList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        if(InputIde.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Selecciona un usuario de la lista para actualizar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        boolean exito = peticion.updateUser(InputUser.getText(), InputPassword.getText(), Integer.parseInt(InputIde.getText()));
        if(exito){
            peticion.selectUser(Table);
            Clean();
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        if(InputUser.getText().trim().isEmpty() || InputPassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor llena los campos de usuario y contraseña.","Advertencia", JOptionPane.WARNING_MESSAGE );
            return;
        }
        boolean exito = peticion.addUser(InputUser.getText(), InputPassword.getText());
        if(exito){
            peticion.selectUser(Table);
            Clean();
        }
    }//GEN-LAST:event_BtnInsertActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        if(InputIde.getText().trim().isEmpty()){
            JOptionPane.showConfirmDialog(this, "Selecciona un usuario de la lista para eliminar.","Advertencia", JOptionPane.WARNING_MESSAGE );
            return;
        }
        boolean exito = peticion.deleteUser(Integer.parseInt(InputIde.getText()));
        if(exito){
            peticion.selectUser(Table);
            Clean();
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void InputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPasswordActionPerformed

    private void BtnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListActionPerformed
        peticion.selectUser(Table);
        System.out.println("Carga de usuarios completa");
    }//GEN-LAST:event_BtnListActionPerformed

    private void InputIdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputIdeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JButton BtnList;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField InputIde;
    private javax.swing.JTextField InputPassword;
    private javax.swing.JTextField InputUser;
    private javax.swing.JLabel LabelIde;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUser;
    private javax.swing.JTable Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
